










apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels: 
    app: wordpress
    purpose: wordpress-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        volumes:
        - ./wp-content:/var/www/html/wp-content
        - ./wp-config.php:/usr/src/wordpress/wp-config-sample.php
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        - name: WORDPRESS_DB_USER
          value: wpuser
        - name: WORDPRESS_DB_PASSWORD
          value: DEVOPS12345
        - name: WORDPRESS_DB_NAME
          value: wpdb
